create table ingredients (is_natural boolean not null, name varchar(255) not null, product_id varchar(255) not null, primary key (name));
create table products (id varchar(255) not null, name varchar(255), primary key (id));
alter table if exists ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products on delete cascade;
create table ingredients (is_natural boolean not null, name varchar(255) not null, product_id varchar(255) not null, primary key (name));
create table products (id varchar(255) not null, name varchar(255), primary key (id));
alter table if exists ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products on delete cascade;
create table ingredients (is_natural boolean not null, name varchar(255) not null, product_id varchar(255) not null, primary key (name));
create table products (id varchar(255) not null, name varchar(255), primary key (id));
alter table if exists ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products on delete cascade;
create table ingredients (is_natural boolean not null, name varchar(255) not null, product_id varchar(255) not null, primary key (name));
create table products (id varchar(255) not null, name varchar(255), primary key (id));
alter table if exists ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products on delete cascade;
create table ingredients (is_natural boolean not null, name varchar(255) not null, product_id varchar(255) not null, primary key (name));
create table products (id varchar(255) not null, name varchar(255), primary key (id));
alter table if exists ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products on delete cascade;
create table ingredients (is_natural boolean not null, name varchar(255) not null, product_id varchar(255) not null, primary key (name));
create table products (id varchar(255) not null, name varchar(255), primary key (id));
alter table if exists ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products on delete cascade;
create table ingredients (is_natural boolean not null, name varchar(255) not null, product_id varchar(255) not null, primary key (name));
create table products (id varchar(255) not null, name varchar(255), primary key (id));
alter table if exists ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products on delete cascade;
create table ingredients (is_natural boolean not null, name varchar(255) not null, product_id varchar(255) not null, primary key (name));
create table products (id varchar(255) not null, name varchar(255), primary key (id));
alter table if exists ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products on delete cascade;
create table ingredients (is_natural boolean not null, name varchar(255) not null, product_id varchar(255) not null, primary key (name));
create table products (id varchar(255) not null, name varchar(255), primary key (id));
alter table if exists ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products on delete cascade;
create table ingredients (is_natural boolean not null, name varchar(255) not null, product_id varchar(255) not null, primary key (name));
create table products (id varchar(255) not null, name varchar(255), primary key (id));
alter table if exists ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products on delete cascade;
